Repository Infomaniak/android-SwissTransfer, pull requests merged in 2024-10, with the labels that each got.

#81 Provide isDarkMode to easily access it anywhere
  app/src/main/java/com/infomaniak/swisstransfer/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
Labels: enhancement, quick

#80 Add basic file picker logic backbone to new transfers
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferFile.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferFilesManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/UploadSourceChoiceBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/FileNameUtils.kt
  app/src/test/java/com/infomaniak/swisstransfer/PostifxedFileNameUnitTest.kt
Labels: enhancement

#83 Fix infomaniak logo on low api
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/LogoInfomaniak.kt
Labels: quick

#98 feat: Add `TransferTypeButtons` component
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Chain.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Envelope.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/QrCode.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/WifiWave.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferTypeScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Dimens.kt
Labels: enhancement

#86 Clean XML files
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/swisstransfer/di/CoroutinesDispatchersModule.kt
  app/src/main/java/com/infomaniak/swisstransfer/di/CoroutinesQualifiers.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/LogoInfomaniak.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/BrandTopAppBarScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentListScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
Labels: quick

#91 feat: Add strings related to Data Management
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: quick

#92 feat: Add images related to Data Management
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/ThemedImage.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/matomo/Matomo.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/matomo/MatomoDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/matomo/MatomoLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/sentry/Sentry.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/sentry/SentryDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/sentry/SentryLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtection.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtectionDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtectionLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/matomo/Matomo.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/matomo/MatomoDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/matomo/MatomoLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/sentry/Sentry.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/sentry/SentryDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/sentry/SentryLight.kt
Labels: quick

#101 feat: Add UploadSuccess Email & QR illustrations
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtectionDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtectionLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessEmail/UploadSuccessEmail.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessEmail/UploadSuccessEmailDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessEmail/UploadSuccessEmailLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessQr/UploadSuccessQr.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessQr/UploadSuccessQrDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessQr/UploadSuccessQrLight.kt
Labels: quick

#102 feat: Add strings related to UploadSuccess feature
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: quick

#106 Bump ST Core to `0.3.0`
  app/src/main/java/com/infomaniak/swisstransfer/ui/MainApplication.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
  gradle/libs.versions.toml
Labels: quick

#110 feat: Add `@PreviewAllWindows`
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/MultiplePreview.kt
Labels: quick

#107 Add loader inside buttons
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
Labels: enhancement

#109 Fix width of double button where only one button is defined
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt
Labels: bug, enhancement, quick

#88 Use a PreviewParameter to factorize FileUiItem instantiation inside previews
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SmallFileItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/previewparameter/FileUiListPreviewParameterProvider.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
Labels: enhancement, quick

#89 Turn FileUiItem from interface to data class to make future replacement easier
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FilePreview.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SmallFileItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/previewparameter/FileUiListPreviewParameterProvider.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentListScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferFilesManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/FileUiItemExt.kt
Labels: quick

#116 fix(ImportScreen): Fix preview
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
Labels: bug

#114 refactor(TransferSettings): Use multiplatform enum values instead of hardcoded ones
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
Labels: enhancement

#119 Rename margins to the new standard shared with iOS
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BrandTopAppBar.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/CrossCircleButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/IllustratedMessageBlock.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/components/ReceivedEmptyFab.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentEmptyScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Margin.kt
Labels: enhancement, quick

#115 feat: Add transfer advanced settings
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SharpRippleButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ChevronRightThick.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/LockedTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SettingItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferAdvancedSetting.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferAdvancedSettings.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Dimens.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#93 Copy imported files to app's local file storage in cache
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/AlreadyUsedFileNamesSet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/FilesMutableStateFlow.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportLocalStorage.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferCountChannel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferFilesManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/FileNameUtils.kt
  app/src/test/java/com/infomaniak/swisstransfer/PostfixedFileNameUnitTest.kt
Labels: enhancement

#130 Fix lifecycle of imported files in new transfer
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
Labels: bug, quick

#131 Move locally imported files to filesDir instead of cacheDir and better name it
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportLocalStorage.kt
Labels: quick

#128 Remove unused import
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/LockedTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/QrCode.kt
Labels: quick

#121 feat: Add swiss transfer title
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#136 Replace local FileUi data class with KMP FileUi model
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FilePreview.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SmallFileItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/previewparameter/FileUiListPreviewParameterProvider.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentListScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/FilesMutableStateFlow.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/FileUiItemExt.kt
Labels: enhancement, quick

#137 Bump ST KMP version
  gradle/libs.versions.toml
Labels: quick

#139 fix: Add `NNBSP` in `getQuantityFromHumanReadableSize(…)`
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/HumanReadableSizeUtils.kt
Labels: bug, quick
