Repository Infomaniak/android-SwissTransfer, pull requests merged in 2024-12, with the labels that each got.

#220 refactor: Polish import screen
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomStickyButtonScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SinglePaneScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferAlertDialog.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/QrCode.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/PasswordOptionAlertDialog.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Dimens.kt
Labels: enhancement

#236 fix: Better BottomBar button spacing for all languages
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
Labels: enhancement

#244 feat: Make the TransferTypeButton go into View at launch and when selected
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/BringIntoViewRow.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt
Labels: enhancement

#248 feat: Replace titleRes with actual string titles in buttons
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomStickyButtonScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferAlertDialog.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferExpiredBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/PasswordBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/QrCodeBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadErrorScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
Labels: enhancement, quick

#251 style: Update Previews names to sort them in the right order
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/MultiplePreviews.kt
Labels: enhancement, quick

#222 feat: Onboarding
  Core2/Compose/Core/build.gradle.kts
  Core2/Compose/Core/consumer-rules.pro
  Core2/Compose/Core/proguard-rules.pro
  Core2/Compose/Core/src/main/java/com/infomaniak/core2/compose/core/ScreenUtils.kt
  Core2/Onboarding/build.gradle.kts
  Core2/Onboarding/consumer-rules.pro
  Core2/Onboarding/proguard-rules.pro
  Core2/Onboarding/src/main/java/com/infomaniak/library/onboarding/HorizontalPagerIndicator.kt
  Core2/Onboarding/src/main/java/com/infomaniak/library/onboarding/OnboardingScaffold.kt
  Core2/gradle/core2.versions.toml
  Core2/src/main/res/values-de/strings.xml
  Core2/src/main/res/values-es/strings.xml
  Core2/src/main/res/values-fr/strings.xml
  Core2/src/main/res/values-it/strings.xml
  Core2/src/main/res/values/strings.xml
  app/build.gradle.kts
  app/src/main/java/com/infomaniak/swisstransfer/ui/MainApplication.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/OnboardingActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/HighlightedText.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferFab.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ArrowRight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/RadialGradientCornerTopLeft.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/RadialGradientCornerTopLeftDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/RadialGradientCornerTopLeftLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/RadialGradientCornerTopRight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/RadialGradientCornerTopRightDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/RadialGradientCornerTopRightLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/StorageCardboardBoxPile.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/StorageCardboardBoxPileDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/StorageCardboardBoxPileLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/ThreeCardsTransferType.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/ThreeCardsTransferTypeDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/ThreeCardsTransferTypeLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/TwoLocksIntertwinedStars.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/TwoLocksIntertwinedStarsDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/TwoLocksIntertwinedStarsLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/AdHeader.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/onboarding/OnboardingScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/onboarding/components/AnimatedOnboardingButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/CustomShapes.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/AccountUtils.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: enhancement

#253 feat: Update logos
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_monochrome.xml
  app/src/main/res/drawable/ic_logo_notification.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: enhancement, quick

#252 refactor: Update networkUnavailable string
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#250 feat: Update import screen design
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SmallFileItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferOptionsTypes.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButton.kt
Labels: enhancement

#234 feat: Add app integrity api
  Core2/AppIntegrity/build.gradle.kts
  Core2/AppIntegrity/consumer-rules.pro
  Core2/AppIntegrity/proguard-rules.pro
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/ApiClientProvider.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/AppIntegrityManager.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/AppIntegrityRepository.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/AppIntegrityRoutes.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/exceptions/ApiException.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/exceptions/AppIntegrityException.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/exceptions/NetworkException.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/exceptions/UnexpectedApiErrorFormatException.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/exceptions/UnknownException.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/models/ApiError.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/models/ApiResponse.kt
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/models/ApiResponseStatus.kt
  Core2/AppIntegrity/src/test/java/com/infomaniak/core2/appintegrity/ApiClientProviderTest.kt
  Core2/gradle/core2.versions.toml
  app/build.gradle.kts
  app/src/main/java/com/infomaniak/swisstransfer/di/SwissTransferInjectionModule.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement

#271 fix: Make transfer lists stop only at the very edge of the lazy column
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItemList.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransfersListWithExpiredBottomSheet.kt
Labels: bug, quick

#277 feat: Split app integrity logic from send transfer logic
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
Labels: enhancement

#280 feat: Merge send transfer states
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
Labels: enhancement

#258 feat: Add EmailAddressTextField
  Core2/src/main/java/com/infomaniak/core2/EmailUtils.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmailAddressChip.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmailsFlowRow.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferChips.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/EmailAddressTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Dimens.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#281 feat: Require recipients and display real data to success screen
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessScreen.kt
Labels: enhancement
