Repository Infomaniak/android-SwissTransfer, pull requests merged in 2024-09, with the labels that each got.

#47 Auto-format drawables code
  app/src/main/res/drawable/flag_es.xml
  app/src/main/res/drawable/flag_fr.xml
  app/src/main/res/drawable/flag_gb.xml
  app/src/main/res/drawable/flag_ge.xml
  app/src/main/res/drawable/flag_it.xml
Labels: enhancement

#46 Format code
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomStickyButtonScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/TwoPaneScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsThemeScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SettingItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SingleSelectOptions.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferTypeScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Type.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ContextExt.kt
Labels: enhancement

#53 Add missing parts in Spain flag
  app/src/main/res/drawable/flag_es.xml
Labels: bug

#45 Clean Icons & Illustrations code
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Add.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowDownCircle.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowLeft.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowUpCircle.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Bell.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/BlackAndWhiteCircle.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/BlackCircle.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Camera.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Checkmark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ChevronRightSmall.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Clock.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Cross.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/FileBadgeArrowDown.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Folder.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/OpenOutside.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/PaintbrushPalette.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/PolaroidLandscape.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Settings.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/SpeechBubble.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/WhiteCircle.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/ArrowCurvedDownright.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/ChainTilted.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/EnvelopeTilted.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/LogoInfomaniak.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/LogoSwissTransfer.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/QrCodeTilted.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/WaveSignalTilted.kt
Labels: enhancement

#49 Simplification of Images usage
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomSheetItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BrandTobAppBar.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferFab.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTobAppBar.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/AppImages.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Add.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ArrowDownCircle.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ArrowLeft.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ArrowUpCircle.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Bell.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/BlackAndWhiteCircle.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/BlackCircle.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Camera.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Checkmark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ChevronRightSmall.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Clock.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Cross.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/FileBadgeArrowDown.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Folder.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/OpenOutside.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/PaintbrushPalette.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/PolaroidLandscape.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Settings.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/SpeechBubble.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/WhiteCircle.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/ArrowCurvedDownright.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/ChainTilted.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/EnvelopeTilted.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/LogoInfomaniak.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/LogoSwissTransfer.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/QrCodeTilted.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/WaveSignalTilted.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsThemeScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SettingItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SingleSelectOptions.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferTypeScreen.kt
Labels: enhancement

#50 Add some missing commas
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomSheetItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomStickyButtonScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BrandTobAppBar.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTobAppBar.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/AppNavigationSuiteScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDurationValidityScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SettingDivider.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferTypeScreen.kt
Labels: enhancement, quick

#51 Rename some Images
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ArrowDownFile.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ArrowOpenOutside.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/CircleBlack.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/CircleBlackAndWhite.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/CircleWhite.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/ArrowDownRightCurved.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsThemeScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SettingItem.kt
Labels: enhancement

#42 Add empty ReceivedScreen
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmptyState.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/ArrowRightCurved.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/MascotSearching.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/components/ReceivedEmptyFab.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentEmptyScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Dimens.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Margin.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#40 Add Theme, ValidityPeriod, DownloadLimit & EmailLanguage settings
  app/build.gradle.kts
  app/src/main/java/com/infomaniak/swisstransfer/di/ApplicationModule.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/MainApplication.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsThemeScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement

#58 Revert modification that makes impossible to build
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
Labels: bug, quick

#66 Fix settings option style
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsThemeScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/OptionScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SingleSelectOptions.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/Titles.kt
Labels: enhancement

#67 Fix top app bar
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTobAppBar.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/OptionScaffold.kt
Labels: bug, enhancement, quick

#70 Use stringResource instead of accessing getString through a context manually
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmptyState.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/components/ReceivedEmptyFab.kt
Labels: enhancement, quick

#71 Hide discovery message when transfer list has at least one item
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/components/ReceivedEmptyFab.kt
Labels: enhancement

#76 Rename `BrandTobAppBar` into `BrandTopAppBar`
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BrandTopAppBar.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/BrandTopAppBarScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/MainScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
Labels: quick

#79 Simplify contentPadding usage
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/BrandTopAppBarScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/SmallWindowTopAppBarScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentEmptyScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentListScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/OptionScaffold.kt
Labels: enhancement, quick
