Repository Infomaniak/android-SwissTransfer, pull requests merged in 2024-11, with the labels that each got.

#120 feat: Add `SwissTransferTextField`
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Eye.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/EyeCrossed.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferAdvancedSettings.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#133 refactor: Clean Icons code & Rename some Illustrations
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/CrossCircleButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/AddThick.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Chain.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/CrossThick.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/DocumentOnDocument.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Envelope.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/LockedTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/PersonBadgeShare.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/QrCode.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/WifiWave.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/beers/Beers.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/beers/BeersDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/beers/BeersLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessEmail/UploadSuccessEmailDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessEmail/UploadSuccessEmailLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessQr/UploadSuccessQr.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
Labels: quick

#142 feat: Add transfer button type state
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt
Labels: enhancement

#145 Connect upload back and UI
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/UploadProgressScreen.kt
Labels: enhancement

#147 chore: Clean unused import
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadAd/MetallicSafeDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadCancelBottomSheet/RedCrossPaperPlanes.kt
Labels: quick

#150 Update upload progress strings key
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressAdType.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: quick

#154 Rename Progress component's file name with the correct name
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/Progress.kt
Labels: quick

#155 Fix crash of new transfer activity
  app/src/main/java/com/infomaniak/swisstransfer/ui/MatomoSwissTransfer.kt
Labels: bug, quick

#144 feat: Add advanced option buttons states
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferOptionsBottomSheets.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferAdvancedSetting.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferAdvancedSettings.kt
Labels: enhancement

#152 Add upload error screen
  Core2/src/main/res/values-de/strings.xml
  Core2/src/main/res/values-es/strings.xml
  Core2/src/main/res/values-fr/strings.xml
  Core2/src/main/res/values-it/strings.xml
  Core2/src/main/res/values/strings.xml
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmptyState.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferExpiredBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadError/GhostMagnifyingGlassQuestionMark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadError/GhostMagnifyingGlassQuestionMarkDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadError/GhostMagnifyingGlassQuestionMarkLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadErrorScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#156 Rename NewTransferViewModel into ImportFilesViewModel
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
Labels: quick

#163 Fix transfert type button's spacing
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt
Labels: quick

#158 Add highlighted text in the title to the upload progress screen
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/HighlightedText.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/AdHeader.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#159 Fix some strings
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: quick

#149 feat: Add password popup
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferAlertDialog.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferOptionsBottomSheets.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/PasswordOptionAlertDialog.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/WeightOneSpacer.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement

#161 Navigate to upload error screen when an error is detected
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
Labels: enhancement

#169 refactor: Rename `transferLink` into `transferUrl`
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/QrCode.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
Labels: quick, rebase

#170 refactor: Extract usage of Emails test data
  app/src/main/java/com/infomaniak/swisstransfer/ui/previewparameter/EmailsPreviewParameterProvider.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
Labels: quick

#171 refactor: Extract `TransfersListWithExpiredBottomSheet` to its own co…
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransfersListWithExpiredBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
Labels: quick

#173 refactor: Extract EmailsFlowRow to its own component
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmailAddressChip.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmailsFlowRow.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
Labels: quick

#172 Connect first advanced settings to upload api call
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
Labels: enhancement, quick

#160 Update share and copy link button's design
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/ShareAndCopyButtons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Dimens.kt
Labels: enhancement

#174 feat: Use real data for repository URL in DataManagement screen
  app/build.gradle.kts
  app/src/main/java/com/infomaniak/swisstransfer/ui/MatomoSwissTransfer.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/UploadSourceChoiceBottomSheet.kt
  app/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: quick

#181 feat: Add transfer message
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
Labels: enhancement

#184 chore: Put back password option to avoid crash
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
Labels: enhancement

#200 Centralize Progress text style
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/Progress.kt
Labels: enhancement, quick

#203 Stop tracking activities in Matomo
  app/src/main/java/com/infomaniak/swisstransfer/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/NewTransferActivity.kt
Labels: enhancement, quick

#204 Remove file choice bottom sheet
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomSheetItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Camera.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/PolaroidLandscape.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/UploadSourceChoiceBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#210 fix: Resume network with old uploaded size
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
Labels: bug

#208 feat: Add a generic button component
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferButton.kt
Labels: enhancement

#213 feat: Improve NavigationRail by adding label
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/AppNavigationSuiteScaffold.kt
Labels: enhancement, quick

#216 fix: HighlighterText's text when the argument is the last characters of the whole string
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/HighlightedText.kt
Labels: bug
