Repository Infomaniak/android-SwissTransfer, pull requests merged in 2025-03, with the labels that each got.

#434 feat: Open to NewTransferActivity if a transfer is in progress
  app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/NewTransferActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/ExternalNavigation.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/LastTransferPreferences.kt
  app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
Labels: enhancement

#452 fix: Improve PickFilesScreen UX
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomStickyButtonScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SinglePaneScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/EmailAddressTextField.kt
Labels: bug, enhancement

#450 feat: Matomo basic
  app/src/main/java/com/infomaniak/swisstransfer/ui/MatomoSwissTransfer.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsThemeScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/OptionScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/NewTransferFilesDetailsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/PickFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadFailureScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadRetryScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/ValidateUserEmailScreen.kt
Labels: enhancement

#457 fix: Use correct illustration for empty state of received screen
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
Labels: quick

#462 fix: Don’t block upload if notification permission is denied
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/PickFilesScreen.kt
Labels: quick

#464 fix: Fix display of download progress
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt
Labels: bug, quick

#465 fix(LinearProgressIndicator): Remove the draw stop indicator
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt
Labels: bug

#467 refactor: Clean code
  app/src/main/java/com/infomaniak/swisstransfer/workers/FileChunkSizeManager.kt
Labels: enhancement
