Repository Infomaniak/android-SwissTransfer, pull requests merged in 2025-01, with the labels that each got.

#296 fix: ShareAndCopy spacing
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
Labels: enhancement, quick

#302 refactor: Sort modules & injections into correct modules
  app/build.gradle.kts
  app/src/main/java/com/infomaniak/swisstransfer/di/ApplicationModule.kt
  app/src/main/java/com/infomaniak/swisstransfer/di/CoroutinesDispatchersModule.kt
  app/src/main/java/com/infomaniak/swisstransfer/di/SwissTransferInjectionModule.kt
  app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
  settings.gradle.kts
Labels: quick

#303 refactor: Rename `TransferTypeUi` enum before using its name
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessScreen.kt
Labels: quick

#309 docs: Add explanatory comment about minification issue
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
Labels: quick

#254 feat: Mail validation screen
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ValidateUserEmailScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressAdType.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/HideSelectAllTextToolbar.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/ValidateUserEmailScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/ValidateUserEmailViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/components/CodeVerification.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/components/OtpTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/components/ResendCodeCountDownButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ContextExt.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/TextUtils.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement

#298 feat: List two more apps in the "open mail app" button
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ContextExt.kt
Labels: enhancement

#255 feat: Add confirmation when trying to leave the new transfer flow
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferAlertDialog.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferButton.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/PasswordBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/PasswordOptionAlertDialog.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadErrorScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/ShareAndCopyButtons.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/components/ResendCodeCountDownButton.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#304 refactor: Move Core2 modules to correct packages
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/AppIntegrityManager.kt
  Core2/Matomo/build.gradle.kts
  Core2/Matomo/src/main/java/com/infomaniak/core2/matomo/Matomo.kt
  Core2/Network/build.gradle.kts
  Core2/Network/src/main/java/com/infomaniak/core2/network/NetworkAvailability.kt
  Core2/Onboarding/build.gradle.kts
  Core2/Onboarding/src/main/java/com/infomaniak/core2/onboarding/HorizontalPagerIndicator.kt
  Core2/Onboarding/src/main/java/com/infomaniak/core2/onboarding/OnboardingScaffold.kt
  Core2/Sentry/build.gradle.kts
  Core2/Sentry/src/main/java/com/infomaniak/core2/sentry/SentryLog.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/MatomoSwissTransfer.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportLocalStorage.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/onboarding/OnboardingScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/workers/UploadFileTask.kt
  app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
Labels: quick

#307 refactor: Sort imports
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/workers/UploadFileTask.kt
  app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
Labels: quick

#313 fix: Make SwissTransfer build again!
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/ValidateUserEmailScreen.kt
Labels: quick

#306 refactor: Rename Compose Core module into Compose Basics
  Core2/Compose/Basics/build.gradle.kts
  Core2/Compose/Basics/consumer-rules.pro
  Core2/Compose/Basics/proguard-rules.pro
  Core2/Compose/Basics/src/main/java/com/infomaniak/core2/compose/basics/ScreenUtils.kt
  app/build.gradle.kts
  app/src/main/java/com/infomaniak/swisstransfer/ui/OnboardingActivity.kt
  settings.gradle.kts
Labels: quick

#308 chore: Remove old unused illustrations
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/ChainTilted.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/EnvelopeTilted.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/QrCodeTilted.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/WaveSignalTilted.kt
Labels: quick

#314 fix: Fix the alert button's disabled state colors
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferButton.kt
Labels: enhancement

#315 feat: Hide the arrow message from "sent" screen about being your first transfer when it's not
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
Labels: enhancement, quick

#299 feat: Opt-out of Matomo & Sentry
  Core2/Matomo/build.gradle.kts
  Core2/Matomo/src/main/java/com/infomaniak/core2/matomo/Matomo.kt
  app/build.gradle.kts
  app/src/main/java/com/infomaniak/swisstransfer/ui/MainApplication.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/MatomoSwissTransfer.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementMatomoScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementSentryScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsMatomoViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsSentryViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/DataManagementPreferences.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/DataStoreUtils.kt
  gradle/libs.versions.toml
Labels: enhancement

#317 fix: Do not report to sentry known errors that are expected to happen
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
Labels: bug, quick

#319 feat: Update chip style to material 3
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferChips.kt
Labels: enhancement, quick

#318 feat: Update the button loader colors and stop showing them as disabled
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferButton.kt
Labels: enhancement

#322 fix: Read if transfers are empty from viewmodel instead of passing down list of transfers
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersViewModel.kt
Labels: enhancement, quick

#320 fix: Avoid having the deeplinks piling in the stacks
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
Labels: bug

#328 fix: Use correct strings for Cancel upload buttons
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, quick

#338 feat: Quick UI fixes
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/NewTransferFab.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTextField.kt
Labels: enhancement, quick

#339 feat: Add possibility to share files to the app
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/NewTransferActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferOpenManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
Labels: enhancement

#341 feat: Prevent file picker from opening when backing after a canceled transfer
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
Labels: bug, quick

#345 chore: Update urlUserReportAndroid string key into urlUserReport
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#351 fix: Use coherent ordering of files when importing files
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/NewTransferFilesDetailsScreen.kt
Labels: enhancement, quick

#350 fix: Do not display file picker when the activity is killed and recreated if it's not needed
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
Labels: bug, quick

#352 fix: Set isFirstViewModelCreation to true
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
Labels: bug, quick

#324 feat: Add transfer sections with sticky headers
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItemList.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransfersListWithExpiredBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/previewparameter/GroupedTransfersPreviewParameterProvider.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/previewparameter/TransferUiListPreviewParameterProvider.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersGroupingManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersViewModel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/infomaniak/swisstransfer/TransferSectionGroupingTest.kt
  app/src/test/java/com/infomaniak/swisstransfer/dataset/TransferSectionGroupingData.kt
Labels: enhancement

#347 feat: Open deeplink that you sent the right way
  app/src/main/java/com/infomaniak/swisstransfer/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationItem.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/DeeplinkViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/MainScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/DeeplinkExt.kt
Labels: enhancement

#356 feat: Constraints the data management switches to our maxSinglePaneWIdth
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementMatomoScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementSentryScreen.kt
Labels: enhancement

#359 feat: Email text field auto add email when leaving field
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/EmailAddressTextField.kt
Labels: enhancement

#363 chore: Update onboarding cardboard box pile illustration to the new version
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/StorageCardboardBoxPileDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/StorageCardboardBoxPileLight.kt
Labels: enhancement, quick

#357 fix: Handle NewTransferActivity task correctly with the sharing of files
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/NewTransferActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadErrorScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
Labels: bug

#373 feat: Refresh transfer list
  app/src/main/java/com/infomaniak/swisstransfer/ui/MainActivity.kt
  gradle/libs.versions.toml
Labels: enhancement

#378 feat: Animate transfers in transfer lists
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwipeToDismissComponent.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItemList.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransfersListWithExpiredBottomSheet.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
Labels: enhancement, quick

#368 feat: Remember and fills in the last used author email when creating a new transfer
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
Labels: enhancement, quick

#371 chore: Make the appIntegrity work in debug
  Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/AppIntegrityManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
Labels: enhancement, quick

#379 refactor: Replace `printStackTrace()` by `SentryLog.w` and rethrow CancellationException
  app/src/main/java/com/infomaniak/swisstransfer/workers/BaseCoroutineWorker.kt
Labels: enhancement, quick

#382 feat: Display recipient in Sent file's detail
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
Labels: enhancement

#386 feat: Let the user leave if we can't cancel the upload successfully
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
Labels: enhancement, quick

#390 fix: Fix double click leading to empty white screen
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
Labels: bug, quick

#392 fix: CancellationException being reported to sentry and triggering onFailedCancellation()
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
Labels: bug, quick

#393 feat: Reduce probability of wrong file sizes when importing them in a new transfer
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
Labels: bug, enhancement

#395 fix: Missing AppSettings in NewTransferActivity when sharing files to the app before user login
  app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
Labels: bug

#396 fix: Keep same display logic in transfer details screen
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/NewTransferFilesDetailsScreen.kt
Labels: quick

#399 feat: Disable transition on 'MainNavHost'
  app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/MainScaffold.kt
Labels: quick

#397 refactor: Clean code
  app/build.gradle.kts
  app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTopAppBar.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItemList.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementMatomoScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementSentryScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownload.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/FilesDetailsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/FilesDetailsViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/EmailAddressTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/components/OtpTextField.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ContextExt.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/DeeplinkExt.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/FileUiExt.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/utils/WindowAdaptativeInfoExt.kt
Labels: quick
