Repository Infomaniak/android-SwissTransfer, pull requests merged in 2025-02, with the labels that each got.

#408 feat: Add missing shield icon in data management setting
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Shield.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
Labels: enhancement, quick

#407 feat: Define the file import progress as amount bytes instead of amount of files
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportLocalStorage.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/SendButtonStatus.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferCountChannel.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
Labels: enhancement

#406 chore: Declare handled config changes
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/FilePreview.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/MainScaffold.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/Progress.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/ValidateUserEmailScreen.kt
  build.gradle.kts
Labels: quick

#415 chore: Update strings mainly for german wording corrections
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#419 feat: Update ad screen font size from 18sp to 20sp
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/AdHeader.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Type.kt
Labels: enhancement

#424 feat: Add a setting item that opens the swisstransfer end-user license agreement EULA
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#427 feat: Hide the number of download on received transfer
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/TransferInfo.kt
Labels: enhancement, quick

#433 refactor: Update Mascot light illustrations + Add missing Mascot dark illustrations
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmptyState.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/components/IllustratedMessageBlock.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/MascotSearching.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/MascotWithMagnifyingGlass.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotDead/MascotDeadDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotDead/MascotDeadLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotSearching/MascotSearching.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotSearching/MascotSearchingDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotSearching/MascotSearchingLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotWithMagnifyingGlass/MascotWithMagnifyingGlass.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotWithMagnifyingGlass/MascotWithMagnifyingGlassDark.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotWithMagnifyingGlass/MascotWithMagnifyingGlassLight.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt
Labels: quick

#438 feat: Update legacy app icon with the swisstransfer logo
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: enhancement, quick

#444 fix(StatusProgress): Fix a crash occurring because of a division by 0
  app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt
Labels: bug, quick
